services:
  api:
    build: .
    container_name: ecommerce-backend
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - backend

networks:
  backend:
    driver: bridge
